<?php

namespace AppBundle\Repository;

/**
 * IndividualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndividualRepository extends \Doctrine\ORM\EntityRepository
{
}
