<?php

namespace AppBundle\Repository;

/**
 * NoteRepository
 * This was auto generated by Doctrine but we extended it by adding the getBetweenDates method.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * This method generates the result and is usable by the Doctrine ORM.
     * What it does is get a start date and end date then get all notes between those dates and returns it.
     * @param \Datetime $start
     * @param \DateTime $end
     * @return mixed
     */
    public function getBetweenDates(\Datetime $start, \DateTime $end)
    {
        // Create datetime variables for the start and end dates.
        $from = new \DateTime($start->format("Y-m-d")." 00:00:00");
        $to   = new \DateTime($end->format("Y-m-d")." 23:59:59");

        // Use these variables in the querybuilder to check the submittedAt field.
        $qb = $this->createQueryBuilder("e");
        $qb
            ->andWhere('e.submittedAt BETWEEN :from AND :to')
            ->setParameter('from', $from )
            ->setParameter('to', $to);
        // Return the result.
        $result = $qb->getQuery()->getResult();
        return $result;
    }
}
