<?php

namespace AppBundle\Repository;

/**
 * ObjectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectiveRepository extends \Doctrine\ORM\EntityRepository
{
}
